export const INCREASE_LIKE_COUNT = 'INCREASE_LIKE_COUNT';
export const INCREASE_LIKE_COUNT_SUCCESS = 'INCREASE_LIKE_COUNT_SUCCESS';
export const INCREASE_LIKE_COUNT_ERROR = 'INCREASE_LIKE_COUNT_ERROR';
